
server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:mysql://localhost:3308/numble-bank?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 20
      read-only: false
      connection-timeout: 3000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true

logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug

